
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Import package
library(dplyr)
library(readr)
```

```{r}
# Read data
irsd_2021 <- read.csv("irsd_raw_2021.csv")

# Read SA2 map (NSW only) + remove offshore
sa2_map_2021 <- read_absmap("sa22021") %>%
  filter(state_name_2021 == "New South Wales") %>%
  filter(!grepl("Lord Howe Island", sa2_name_2021, ignore.case = TRUE))
```

```{r}
names(irsd_2021)
```

```{r}
# Remove NA column
irsd_2021 <- irsd_2021 %>% select(where(~ !all(is.na(.))))

names(irsd_2021)

# Clean variables
irsd_nsw_2021 <- irsd_2021 %>%
  # Filter NSW
  
   filter(State == "NSW") %>%
   rename_with(~ gsub("\\.+", "_", tolower(.x))) %>%

  # Only keep necessary variables
  select(x2021_statistical_area_level_2_sa2_9_digit_code,
         x2021_statistical_area_level_2_sa2_name,
         score,
         rank_1,
         decile_1,
         percentile_1) %>%

  # Rename selected variables
  rename(sa2_code_2021 = x2021_statistical_area_level_2_sa2_9_digit_code,
         sa2 = x2021_statistical_area_level_2_sa2_name,
         irsd_score = score,
         rank_nsw = rank_1,
         irsd_decile = decile_1,
         irsd_percentile = percentile_1)

# Check cleaned variables
names(irsd_nsw_2021)
```

```{r}
irsd_nsw_clean_2021 <- irsd_nsw_2021 %>%
  left_join(sa2_map_2021 %>% mutate(sa2_code_2021 = parse_integer(sa2_code_2021)),
    by = "sa2_code_2021") %>%
  select(sa2_name_2021,
         irsd_score,
         rank_nsw,
         irsd_decile,
         irsd_percentile)
```

```{r}
# write.csv(irsd_nsw_clean_2021, "irsd_nsw_2021.csv", row.names = FALSE)
```

