
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(readr)
library(dplyr)
library(tidyr)
```


```{r, include=FALSE}
# Read datasets (variables from prepossessing folder)
pop_nsw_2021 <- read.csv("pop_size_nsw_2021.csv")
age_group_nsw_2021 <- read.csv("age_group_nsw_2021.csv")
sex_nsw_2021 <- read.csv("sex_nsw_2021.csv")
cob_nsw_2021 <- read.csv("cob_nsw_2021.csv")
lagge_spk_nsw_2021 <- read.csv("lagge_spk_nsw_2021.csv")
family_compo_nsw_2021 <- read.csv("family_compo_nsw_2021.csv")
```

```{r}
# Read column names
names(age_group_nsw_2021)
names(sex_nsw_2021)
names(cob_nsw_2021)
names(lagge_spk_nsw_2021)
names(family_compo_nsw_2021)
```

```{r}
# Unify format
age_group_nsw_2021 <- age_group_nsw_2021 %>%
  rename(
    `age_0_9` = X0.9.years,
    `age_10_19` = X10.19.years,
    `age_20_29` = X20.29.years,
    `age_30_39` = X30.39.years,
    `age_40_49` = X40.49.years,
    `age_50_59` = X50.59.years,
    `age_60_69` = X60.69.years,
    `age_70_79` = X70.79.years,
    `age_80_89` = X80.89.years,
    `age_90_99` = X90.99.years,
    `age_100_plus` = X100.years.and.over
  )

sex_nsw_2021 <- sex_nsw_2021 %>%
  rename(
    male = Male,
    female = Female
  )

cob_nsw_2021 <- cob_nsw_2021 %>%
  rename(
    australia = "Australia..includes.External.Territories.",
    supplementary_codes_cob = "Supplementary.codes",
    not_stated_cob = "Not.stated"
  )


lagge_spk_nsw_2021 <- lagge_spk_nsw_2021 %>%
  rename(
    english = English,
    supplementary_codes_lagge_spk = "Supplementary.codes",
    not_stated_lagge_spk = "Not.stated"
  )

family_compo_nsw_2021 <- family_compo_nsw_2021 %>%
  rename(
    couple_no_children = `Couple.family.with.no.children`,
    couple_with_children = `Couple.family.with.children`,
    one_parent = `One.parent.family`,
    other_family = `Other.family`,
    not_applicable_family_compo = `Not.applicable`
  )
```

```{r}
# Join variables into pop_nsw datasets
pop_nsw_2021 <- pop_nsw_2021 %>%
  rename(sa2 = "sa2_name_2021") %>%
  left_join(age_group_nsw_2021, by = "sa2") %>%
  left_join(sex_nsw_2021, by = "sa2") %>%
  left_join(cob_nsw_2021, by = "sa2") %>%
  left_join(lagge_spk_nsw_2021, by = "sa2") %>%
  left_join(family_compo_nsw_2021, by = "sa2") 
```

```{r}
# Extract all overseas columns
overseas_cols  <- setdiff(
  names(select(cob_nsw_2021, where(is.numeric))),
  c("australia", "supplementary_codes_cob", "not_stated_cob")
)

# Extract all non-english columns
non_english_cols <- setdiff(
  names(select(lagge_spk_nsw_2021, where(is.numeric))),
  c("english", "supplementary_codes_lagge_spk", "not_stated_lagge_spk")
)
```


```{r}
demographics_nsw_2021 <- pop_nsw_2021 %>%
  mutate(
    
    # Collapse age_group
    age_0_19 = rowSums(across(c(age_0_9, age_10_19)), na.rm = TRUE),
    age_20_39 = rowSums(across(c(age_20_29, age_30_39)), na.rm = TRUE),
    age_40_59 = rowSums(across(c(age_40_49, age_50_59)), na.rm = TRUE),
    age_60_plus = rowSums(across(c(age_60_69, age_70_79, age_80_89, age_90_99, age_100_plus)), na.rm = TRUE),
    
    # Collapse country of birth
    overseas = rowSums(across(any_of(overseas_cols)),na.rm = TRUE),
 
    # Collapse language spoken at home
    non_english = rowSums(across(any_of(non_english_cols)),na.rm = TRUE)
  )
```

```{r}
demographics_nsw_2021 <- demographics_nsw_2021 %>%
  mutate(
    # Adjust denominators
    denominator_family_compo = pop_size - not_applicable_family_compo,
    
    # Calculate proportions (age_group)
    prop_age_0_9 = if_else(pop_size > 0, age_0_9 / pop_size, NA_real_),
    prop_age_10_19 = if_else(pop_size > 0, age_10_19 / pop_size, NA_real_),
    prop_age_20_29 = if_else(pop_size > 0, age_20_29 / pop_size, NA_real_),
    prop_age_30_39 = if_else(pop_size > 0, age_30_39 / pop_size, NA_real_),
    prop_age_40_49 = if_else(pop_size > 0, age_40_49 / pop_size, NA_real_),
    prop_age_50_59 = if_else(pop_size > 0, age_50_59 / pop_size, NA_real_),
    
    prop_age_0_19 = if_else(pop_size > 0, age_0_19 / pop_size, NA_real_),
    prop_age_20_39 = if_else(pop_size > 0, age_20_39 / pop_size, NA_real_),
    prop_age_40_59 = if_else(pop_size > 0, age_40_59 / pop_size, NA_real_),
    prop_age_60_plus = if_else(pop_size > 0, age_60_plus / pop_size, NA_real_),
    
    # Calculate proportions (sex)
    prop_male = if_else(pop_size > 0, male / pop_size, NA_real_),
    prop_female = if_else(pop_size > 0, female / pop_size, NA_real_),
    
    # Calculate proportions (country of birth)
    prop_australia = if_else(pop_size > 0, australia / pop_size, NA_real_),
    prop_overseas = if_else(pop_size > 0, overseas / pop_size, NA_real_),
    
    # Calculate proportions (language spoken at home)
    prop_english = if_else(pop_size > 0, english / pop_size, NA_real_),
    prop_non_english = if_else(pop_size > 0, non_english / pop_size, NA_real_),
    
    # Calculate proportions (family composition)
    prop_couple_no_children = if_else(denominator_family_compo > 0, couple_no_children / denominator_family_compo, NA_real_),
    prop_couple_with_children = if_else(denominator_family_compo > 0, couple_with_children / denominator_family_compo, NA_real_),
    prop_one_parent = if_else(denominator_family_compo > 0, one_parent / denominator_family_compo, NA_real_),
    prop_other_family = if_else(denominator_family_compo > 0, other_family / denominator_family_compo, NA_real_)
  )
```

```{r}
# Retain key variables
demographics_nsw_2021 <- demographics_nsw_2021 %>%
  select(
    sa2, in_wslhd, in_metro, pop_size,
    
    # Age groups
    age_0_9, age_10_19, age_20_29, age_30_39, age_40_49, age_50_59, 
    age_0_19, age_20_39, age_40_59, age_60_plus,
    
    # Sex
    male, female,
    
    # Country of birth
    australia, overseas,
    
    # Language spoken at home
    english, non_english,
    
    # Family composition
    couple_no_children, couple_with_children, one_parent, other_family,
    
    # Proportions
    prop_age_0_9, prop_age_10_19, 
    prop_age_20_29, prop_age_30_39, 
    prop_age_40_49, prop_age_50_59, 
    prop_age_0_19,
    prop_age_20_39,
    prop_age_40_59,
    prop_age_60_plus,
    
    prop_male, prop_female,
    prop_australia, prop_overseas,
    prop_english, prop_non_english,
    prop_couple_no_children, prop_couple_with_children, prop_one_parent, prop_other_family
  ) %>%

  rename(sa2_name_2021 = "sa2")

# write_csv(demographics_nsw_2021, "demographics_nsw_2021.csv")
```

