
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Import package
library(dplyr)
library(readr)
```

```{r}
# Check invalid lines for head and tail
all_lines <- readLines("whether_asthma_raw_2021.csv")
length(all_lines) 
head(all_lines, 11)
tail(all_lines, 9)
```

```{r}
# Remove invalid lines
clean_lines <- all_lines[10:(length(all_lines) - 9)]

# define temporary file name
temp_file <- "whether_asthma_temp_2021.csv"

# Save temporary file for document
writeLines(clean_lines, temp_file)

# read temporary file
whether_asthma_2021 <- read_csv(temp_file)

# Display data frame
head(whether_asthma_2021)
```

```{r}
# Remove NA column
whether_asthma_2021 <- whether_asthma_2021 %>% select(where(~ !all(is.na(.))))

# Remove 'Total' column
whether_asthma_2021 <- whether_asthma_2021 %>% select(-Total)

# Remove 'SA2 (UR)' row
whether_asthma_2021 <- whether_asthma_2021 %>% filter(.[[1]] != "SA2 (UR)")

# Rename sa2 
whether_asthma_2021 <- whether_asthma_2021 %>% rename(sa2 = 'HASTP Whether has Asthma')

# Check data frame
head(whether_asthma_2021)

write_csv(whether_asthma_2021, "whether_asthma_nsw_2021.csv")
```

```{r}
# Read wslhd sa2 file
wslhd_sa2_2021 <- read_csv('wslhd_sa2_2021.csv')

# Filter wslhd data for whether_asthma_2021
whether_asthma_wslhd_2021 <- whether_asthma_2021 %>%
  semi_join(wslhd_sa2_2021, by = "sa2")

# Check data frame
head(whether_asthma_wslhd_2021)
nrow(whether_asthma_wslhd_2021)

# Save wslhd whether_asthma_2021 for document
write_csv(whether_asthma_wslhd_2021, "whether_asthma_wslhd_2021.csv")
```

