```{r, include=FALSE}
library(dplyr)
library(tidyr)
library(strayr)
library(sf)
library(ggplot2)
library(leaflet)
library(htmlwidgets)
library(htmltools)
library(mapview)  
library(webshot2)  
```

```{r, echo=FALSE, message=FALSE}
# Read in population data
pop_size_metro_2021 <- read.csv("data/pop_size_nsw_2021.csv") %>%
  filter(in_metro == 1)

# Read in the SA2-to-LGA-to-LHD mapping table
geo_nsw_2021 <- read.csv("data/sa2_lga_lhd_nsw_2021.csv") 

# Read SA2 map (NSW only) + remove offshore
sa2_map_2021 <- read_absmap("sa22021") %>%
  filter(state_name_2021 == "New South Wales") %>%
  filter(!grepl("Lord Howe Island", sa2_name_2021, ignore.case = TRUE)) %>%
  st_make_valid()

# Read LGA map (NSW only)
lga_map_2021 <- read_absmap("lga2021") %>%
  filter(state_name_2021 == "New South Wales") %>%
  st_make_valid()

# Read LHD map (NSW LHDs 2023)
lhd_map_2023 <- read_absmap("nsw_lhd2023") %>%
  st_make_valid()
```

```{r, include=FALSE}
# Keep six metropolitan LHDs
metro_nsw_lhd <- c(
  "Nepean Blue Mountains","Northern Sydney",
  "South Eastern Sydney","South Western Sydney",
  "Sydney","Western Sydney"
)

wslhd_names <- c("Western Sydney")

# SA2 set in the six metropolitan LHDs
sa2_set <- geo_nsw_2021 %>%
  filter(nsw_lhd_name %in% metro_nsw_lhd) %>%
  pull(sa2_name_2021) %>%
  unique()

# SA2 geometries (metro only)
sa2_metro <- sa2_map_2021 %>%
  filter(sa2_name_2021 %in% sa2_set)

# LGA set in the six metropolitan LHDs
lga_set <- geo_nsw_2021 %>%
  filter(nsw_lhd_name %in% metro_nsw_lhd) %>%
  pull(lga_name_2021) %>%
  unique()

# LGA/LHD geometries (metro only)
lga_metro_2021 <- lga_map_2021 %>%
  filter(lga_name_2021 %in% lga_set)

lhd_metro_2021 <- lhd_map_2023 %>%
  filter(nsw_lhd_name %in% metro_nsw_lhd)
```

```{r, include=FALSE}
# Join map (SA2 + population)
map_pop_metro_2021 <- sa2_metro %>%
  left_join(pop_size_metro_2021, by = "sa2_name_2021")
```

```{r, include=FALSE}
# Ensure LGA/LHD CRS matches SA2
lga_metro_2021 <- st_transform(lga_metro_2021, st_crs(sa2_metro))
lhd_metro_2021 <- st_transform(lhd_metro_2021, st_crs(sa2_metro))

# Rebuild mask from (valid) SA2 metro polygons
metro_mask <- sa2_metro %>%
  st_make_valid() %>%
  st_union() %>%
  st_make_valid()

# Clip to mask (and clean)
lga_clip <- lga_metro_2021 %>%
  st_intersection(metro_mask) %>%
  st_collection_extract("POLYGON", warn = FALSE) %>%
  filter(!st_is_empty(geometry))

lhd_clip <- lhd_metro_2021 %>%
  st_intersection(metro_mask) %>%
  st_collection_extract("POLYGON", warn = FALSE) %>%
  filter(!st_is_empty(geometry)) %>%
  group_by(nsw_lhd_name) %>%         
  summarise(do_union = FALSE, .groups = "drop") %>%
  st_make_valid()

lhd_ll <- st_transform(lhd_clip, 4326)
lga_ll <- st_transform(lga_clip, 4326)
```


```{r}
bbox_metro <- as.list(st_bbox(lhd_ll))
aus <- list(xmin = 110, ymin = -45, xmax = 155, ymax = -8)

metro_map_1 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,   
    zoomControl     = TRUE,    
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,    
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  setView(lng = 150.0, lat = -34, zoom = 9)  %>%
  setMaxBounds(aus$xmin, aus$ymin, aus$xmax, aus$ymax)
```

```{r}
mapshot(
 metro_map_1,
 file   = "metro_map_1.png",
 vwidth = 2500,   
 vheight= 1500
)
```


```{r}
metro_map_2 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,   
    zoomControl     = TRUE,    
    scrollWheelZoom = FALSE,  
    doubleClickZoom = TRUE, 
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE

  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%

  addPolygons(
    data        = lhd_ll,
    fill   = FALSE,           
    color  = "#7C3AED",       
    weight = 5,
    label       = ~ nsw_lhd_name
  ) %>%

  setView(lng = 150.0, lat = -34, zoom = 9)  %>%
  setMaxBounds(aus$xmin, aus$ymin, aus$xmax, aus$ymax)
```


```{r}
mapshot(
 metro_map_2,
 file   = "metro_map_2.png",
 vwidth = 2500, 
 vheight= 1500
)
```



```{r}
metro_map_3 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,    
    scrollWheelZoom = FALSE, 
    doubleClickZoom = TRUE,   
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
  data        = lhd_ll,
  fillColor   = ~ ifelse(nsw_lhd_name == "Western Sydney", "#F59E0B", NA),
  fillOpacity = ~ ifelse(nsw_lhd_name == "Western Sydney", 0.5, 0),  
  color       = "#7C3AED",
  weight      = 5,
  label       = ~ as.character(nsw_lhd_name)
) %>%

  setView(lng = 150.0, lat = -34, zoom = 9)  %>%
  setMaxBounds(aus$xmin, aus$ymin, aus$xmax, aus$ymax)

```


```{r}
mapshot(
 metro_map_3,
 file   = "metro_map_3.png",
 vwidth = 2500,  
 vheight= 1500
)
```

```{r}
wslhd_subset <- subset(lhd_ll, nsw_lhd_name == "Western Sydney")
bbox_wslhd <- as.list(sf::st_bbox(wslhd_subset))
wslhd_ll <- lhd_ll %>% filter(nsw_lhd_name == "Western Sydney")

wslhd_map_1 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
    data   = wslhd_ll,
    fill   = FALSE,         
    color  = "#7C3AED",     
    weight = 5,
    label  = ~ as.character(nsw_lhd_name)
  ) %>%
  fitBounds(bbox_wslhd$xmin, bbox_wslhd$ymin, bbox_wslhd$xmax, bbox_wslhd$ymax)
```

```{r}
mapshot(
 wslhd_map_1,
 file   = "wslhd_map_1.png",
 vwidth = 2500,
 vheight= 1500
)
```

```{r, warning=FALSE}
lga_in_wslhd <- c("Blacktown", "Cumberland", "Parramatta", "The Hills Shire")

lga_wslhd_ll <- lga_ll %>%
  filter(lga_name_2021 %in% lga_in_wslhd) %>%
  st_intersection(sf::st_union(wslhd_ll)) %>%
  st_make_valid() %>%
  group_by(lga_name_2021) %>%
  summarise(.groups = "drop")

wslhd_map_2 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
    data   = lga_wslhd_ll,
    fill   = FALSE,          
    color  = "#7C3AED",        
    weight = 5,
    label  = ~ as.character(lga_name_2021),
  ) %>%
  fitBounds(bbox_wslhd$xmin, bbox_wslhd$ymin, bbox_wslhd$xmax, bbox_wslhd$ymax)

```


```{r}
mapshot(
 wslhd_map_2,
 file   = "wslhd_map_2.png",
 vwidth = 2500,
 vheight= 1500
)
```

```{r}
wslhd_map_3 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
    data   = lga_wslhd_ll,
    fill   = FALSE,          
    color  = "#7C3AED",        
    weight = 5,
    label  = ~ as.character(lga_name_2021),
  ) %>%
  addPolygons(
  data        = filter(lga_wslhd_ll, lga_name_2021 == "Blacktown"),
  fillColor   = "#F59E0B",  
  fillOpacity = 0.5,       
  color       = "#B45309",   
  weight      = 4,           
  label       = ~ as.character(lga_name_2021)
) %>%
  fitBounds(bbox_wslhd$xmin, bbox_wslhd$ymin, bbox_wslhd$xmax, bbox_wslhd$ymax)
```

```{r}
mapshot(
 wslhd_map_3,
 file   = "wslhd_map_3.png",
 vwidth = 2500,
 vheight= 1500
)
```


```{r}
wslhd_map_4 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
    data   = lga_wslhd_ll,
    fill   = FALSE,          
    color  = "#7C3AED",        
    weight = 5,
    label  = ~ as.character(lga_name_2021),
  ) %>%
  addPolygons(
  data        = filter(lga_wslhd_ll, lga_name_2021 == "The Hills Shire"),
  fillColor   = "#F59E0B",  
  fillOpacity = 0.5,       
  color       = "#B45309",   
  weight      = 4,           
  label       = ~ as.character(lga_name_2021)
) %>%
  fitBounds(bbox_wslhd$xmin, bbox_wslhd$ymin, bbox_wslhd$xmax, bbox_wslhd$ymax)
```

```{r}
mapshot(
 wslhd_map_4,
 file   = "wslhd_map_4.png",
 vwidth = 2500,
 vheight= 1500
)
```



```{r}
wslhd_map_5 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
    data   = lga_wslhd_ll,
    fill   = FALSE,          
    color  = "#7C3AED",        
    weight = 5,
    label  = ~ as.character(lga_name_2021),
  ) %>%
  addPolygons(
  data        = filter(lga_wslhd_ll, lga_name_2021 == "Parramatta"),
  fillColor   = "#F59E0B",  
  fillOpacity = 0.5,       
  color       = "#B45309",   
  weight      = 4,           
  label       = ~ as.character(lga_name_2021)
) %>%
  fitBounds(bbox_wslhd$xmin, bbox_wslhd$ymin, bbox_wslhd$xmax, bbox_wslhd$ymax)
```

```{r}
mapshot(
 wslhd_map_5,
 file   = "wslhd_map_5.png",
 vwidth = 2500,
 vheight= 1500
)
```


```{r}
wslhd_map_6 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
    data   = lga_wslhd_ll,
    fill   = FALSE,          
    color  = "#7C3AED",        
    weight = 5,
    label  = ~ as.character(lga_name_2021),
  ) %>%
  addPolygons(
  data        = filter(lga_wslhd_ll, lga_name_2021 == "Cumberland"),
  fillColor   = "#F59E0B",  
  fillOpacity = 0.5,       
  color       = "#B45309",   
  weight      = 4,           
  label       = ~ as.character(lga_name_2021)
) %>%
  fitBounds(bbox_wslhd$xmin, bbox_wslhd$ymin, bbox_wslhd$xmax, bbox_wslhd$ymax)
```

```{r}
mapshot(
 wslhd_map_6,
 file   = "wslhd_map_6.png",
 vwidth = 2500,
 vheight= 1500
)
```

```{r}
hospitals <- data.frame(
  name = c(
    "Westmead Hospital",
    "Blacktown Hospital",
    "Mount Druitt Hospital",
    "Auburn Hospital",
    "Cumberland Hospital"
  ),
  lat = c(
    -33.8045,  # Westmead
    -33.7756,  # Blacktown
    -33.7658,  # Mount Druitt
    -33.8605,  # Auburn
    -33.8019   # Cumberland
  ),
  lng = c(
    150.9886,  # Westmead
    150.9175,  # Blacktown
    150.8297,  # Mount Druitt
    151.0336,  # Auburn
    150.9950   # Cumberland
  )
)


rx_icon <- awesomeIcons(
  icon        = "plus",      
  library     = "fa",
  markerColor = "white",    
  iconColor   = "#DC2626" 
)

wslhd_map_7 <- leaflet(
  height = "100vh",
  options = leafletOptions(
    dragging        = FALSE,
    zoomControl     = TRUE,
    scrollWheelZoom = FALSE,
    doubleClickZoom = TRUE,
    boxZoom         = FALSE,
    keyboard        = FALSE,
    touchZoom       = FALSE
  )
) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik,
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(
    data   = lga_wslhd_ll,
    fill   = FALSE,          
    color  = "#7C3AED",        
    weight = 5,
    label  = ~ as.character(lga_name_2021),
  ) %>%
  addAwesomeMarkers(
    data = hospitals, lng = ~lng, lat = ~lat, label = ~name,
    popup = ~sprintf("<b>%s</b><br/>lat: %.6f<br/>lng: %.6f", name, lat, lng),
    icon = rx_icon) %>%
  fitBounds(bbox_wslhd$xmin, bbox_wslhd$ymin, bbox_wslhd$xmax, bbox_wslhd$ymax)
```

```{r}
mapshot(
 wslhd_map_7,
 file   = "wslhd_map_7.png",
 vwidth = 2500,
 vheight= 1500
)
```