
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(dplyr)
library(tidyr)
library(strayr)
library(sf)
library(ggplot2)
```

```{r, echo=TRUE}
# Read in population data
pop_size_metro_2021 <- read.csv("pop_size_nsw_2021.csv") %>%
  filter(in_metro == 1)

# Read in the SA2-to-LGA-to-LHD mapping table
geo_nsw_2021 <- read.csv("sa2_lga_lhd_nsw_2021.csv") 

# Read SA2 map
sa2_map_2021 <- read_absmap("sa22021") %>%
  filter(state_name_2021 == "New South Wales") %>%
  
  # Remove offshore
  filter(!grepl("Lord Howe Island", sa2_name_2021, ignore.case = TRUE))

# Read LGA map
lga_map_2021 <- read_absmap("lga2021") %>%
  filter(state_name_2021 == "New South Wales") 

# Read LHD map
lhd_map_2023 <- read_absmap("nsw_lhd2023") 
```

```{r, include=FALSE}
# Keep six metropolitan LHDs
metro_nsw_lhd <- c(
  "Nepean Blue Mountains","Northern Sydney",
  "South Eastern Sydney","South Western Sydney",
  "Sydney","Western Sydney"
)

# SA2 set in the six metropolitan LHDs
sa2_set <- geo_nsw_2021 %>%
  filter(nsw_lhd_name %in% metro_nsw_lhd) %>%
  pull(sa2_name_2021) %>%
  unique()

# SA2 geometries (metro only)
sa2_metro <- sa2_map_2021 %>%
  filter(sa2_name_2021 %in% sa2_set)

# LGA set in the six metropolitan LHDs
lga_set <- geo_nsw_2021 %>%
  filter(nsw_lhd_name %in% metro_nsw_lhd) %>%
  pull(lga_name_2021) %>%
  unique()

# LGA/LHD geometries (metro only)
lga_metro_2021 <- lga_map_2021 %>%
  filter(lga_name_2021 %in% lga_set)

lhd_metro_2021 <- lhd_map_2023 %>%
  filter(nsw_lhd_name %in% metro_nsw_lhd)
```

```{r, include=FALSE}
# Join map 
map_pop_metro_2021 <- sa2_metro %>%
  left_join(pop_size_metro_2021, by = "sa2_name_2021")
```

```{r, include=FALSE}
# make sure CRS matches SA2
lga_metro_2021 <- st_transform(lga_metro_2021, st_crs(sa2_metro))
lhd_metro_2021 <- st_transform(lhd_metro_2021, st_crs(sa2_metro))

# union of metro SA2 as clipping mask
metro_mask <- sa2_metro %>%
  st_union() %>%
  st_make_valid()

# intersection (clip to mask)
lga_clip <- st_intersection(lga_metro_2021, metro_mask)
lhd_clip <- st_intersection(lhd_metro_2021, metro_mask)

# bbox for coord_sf
bbox <- st_bbox(sa2_metro)
```

```{r}
# Plot
pop_fill_scale <- function() {
  scale_fill_viridis_c(
    option = "plasma",
    name   = "Population Size",
    limits = c(10000, 25000),
    breaks = c(10000, 15000, 20000, 25000),
    labels = scales::comma,
    oob    = scales::squish,
  )
}

ggplot(map_pop_metro_2021) +
  geom_sf(aes(fill = pop_size), color = "black", linewidth = 0.1) +
  geom_sf(data = lga_clip, fill = NA, color = "red", linewidth = 0.4) +
  geom_sf(data = lhd_clip, fill = NA, color = "lightblue", linewidth = 0.4) +
  pop_fill_scale() +
  labs(title = "NSW Metropolitan Local Health Districts Population Size Map (Cencus 2021)") +
  coord_sf(
    xlim = c(bbox["xmin"], bbox["xmax"]),
    ylim = c(bbox["ymin"], bbox["ymax"]),
    expand = FALSE
  ) +
  theme_minimal() +
  theme(
    panel.grid      = element_blank(),
    axis.text       = element_blank(),
    axis.ticks      = element_blank(),
    axis.title      = element_blank(),
    legend.position = "right"
  )
```

