---
Description: Calculate NSW SA2 population and flag WSLHD and metropolitan areas
Approach: Select `Total` Column as `pop_size` from age group raw data file
author: "Zachary Xie"
date: "2025-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readr)
```

```{r}
# Check invalid lines for head and tail
all_lines <- readLines("age_group_raw_2021.csv")
length(all_lines) 
head(all_lines, 10)
tail(all_lines, 9)

# Remove invalid lines
clean_lines <- all_lines[10:(length(all_lines) - 9)]

# define temporary file name
temp_file <- "age_group_temp_2021.csv"

# Save temporary file for document
writeLines(clean_lines, temp_file)
```

```{r}
# read temporary file
age_group_2021 <- read_csv(temp_file)

# Remove NA column
age_group_2021 <- age_group_2021 %>% select(where(~ !all(is.na(.))))

# Remove 'SA2 (UR)' row
age_group_2021 <- age_group_2021 %>% filter(.[[1]] != "SA2 (UR)")

# Rename sa2 
age_group_2021 <- age_group_2021 %>% rename(sa2 = 'AGE10P Age in Ten Year Groups')

# Check data frame
head(age_group_2021)
```

```{r}
# Read NSW SA2 data
geo_nsw_2021 <- read.csv("sa2_lga_lhd_nsw_2021.csv")

# Filter WSLHD
geo_wslhd_2021 <- read.csv("sa2_lga_wslhd_2021.csv")

# Define the NSW metropolitan list
metro_nsw_lhd <- c("Nepean Blue Mountains",
                   "Northern Sydney",
                   "South Eastern Sydney",
                   "South Western Sydney",
                   "Sydney","Western Sydney")

# Filter metropolitan 
geo_metro_2021 <- geo_nsw_2021 %>%
  filter(nsw_lhd_name %in% metro_nsw_lhd)
```

```{r}
# Select `total`
pop_size_nsw_2021 <- age_group_2021 %>%
  select(sa2, Total) %>%
  rename(
    `sa2_name_2021` = sa2,
    `pop_size` = Total)

# Flag WSLHD and metropolitan areas
pop_size_nsw_2021 <- pop_size_nsw_2021 %>%
  mutate(in_wslhd = if_else(sa2_name_2021 %in% geo_wslhd_2021$sa2_name_2021, 1, 0)) %>%
  mutate(in_metro = if_else(sa2_name_2021 %in% geo_metro_2021$sa2_name_2021, 1, 0)) %>%
  select(sa2_name_2021, in_wslhd, in_metro, pop_size)

# Save pop_nsw_2021 for document
# write_csv(pop_size_nsw_2021, "pop_size_nsw_2021.csv")
```

